package org.trevershick.plebiscite.engine.impl;

import org.trevershick.plebiscite.engine.State;
import org.trevershick.plebiscite.model.Ballot;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="Ballots")
public class DynamoDbBallot implements Ballot {
	private String id;
	private String title;
	private String description;
	private State state = State.Closed;
	private Integer version;
	
	
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "Id")
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    
    @DynamoDBVersionAttribute(attributeName="Version")
    public Integer getVersion() {
    	return this.version;
    }
    public void setVersion(Integer value) {
    	this.version = value;
    }
    

    @DynamoDBAttribute(attributeName="Title")
    public String getTitle() { return title; }
    public void setTitle(String title) { 
    	this.title = title;
    	if (this.description == null) {
    		setDescription(title);
    	}
    }
    
    @DynamoDBAttribute(attributeName="Description")
    public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
    @DynamoDBAttribute(attributeName="State")
    public String getStateAsString() { return state.name(); }
    public void setStateAsString(String value) {
    	try {
    		setState(State.valueOf(value));
    	} catch (Exception e) {
    		setState(State.Closed);
    	}
    }
    		

	@DynamoDBIgnore
	public State getState() {
		return state;
	}
	public void setState(State state) {
		this.state = state;
	}


    
}
